### ISSUE TITLE
Wagtail | database | urls and news

### ISSUE THREAD

**Issue by Hadi-Khatib** [nikonikoniko/syrianarchive#21]
text added to the field [urls and news] and the field [source] in wagtail doesn't show on the database 
![1](https://cloud.githubusercontent.com/assets/8692315/17835493/67c492c8-676f-11e6-9e2a-878b3eeeda09.png) unless we add it through django-admin database then it shows.

**Comment by nikonikoniko** [comment]
This seems to work perfectly fine for me... give it another shot.

there is no field called "source" -- do you mean "source connection" ? or "video source" ?

**Comment by Hadi-Khatib** [comment]
The "source" is = "Acquired from" field on the database.
