### ISSUE TITLE
Weapon used = none

### ISSUE THREAD

**Issue by Hadi-Khatib** [nikonikoniko/syrianarchive#26]
The type of weapon used doesn't appear on the database even if it was selected. Screenshot attached. 
![screen shot 2016-10-19 at 11 36 43 pm](https://cloud.githubusercontent.com/assets/8692315/19538709/9ece79b8-9655-11e6-9ebe-33670545c9c9.png)

**Comment by nikonikoniko** [comment]
There are some fields we decided not to use any more.

SO, would you like it away from the front end or back in the back end?
